export interface Employee {
    id: number
    fullName: string
    code: string
    email: string
    specialization: string
    phoneNumber: string
    hireDate: string
    status: string
    nationalId: string
    maritalStatus: string
    address: string
    gender: string
    notes: string
    attachmentsUrls: string[]
    jobTitleId: number
    jobTitleName: string
    jobTypeId: number
    jobTypeName: string
    jobLevelId: number
    jobLevelName: string
    jobDepartmentId: number
    jobDepartmentName: string
    branchId: number
    branchName: string
    variableSalary: number
    visaCode: string
    allowances: number
    rewards: number
    basicSalary: number
    tax: number
    insurance: number
    vacationDays: number
    isAuthorized: boolean
    createdById: string
    createdBy: string
    createdOn: string
    updatedById: any
    updatedBy: any
    updatedOn: any
}  